name: ci-go-lang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go test ./...
      - run: go run cmd/main.go
      - run: go test -coverprofile=coverage.out ./...
      - run: go tool cover -func=coverage.out
      - run: go tool cover -html=coverage.out -o coverage.html
